#!/usr/bin/env python3

import os
import click
from commands import get, put, subscribe

HOST = os.getenv("HOST", "http://localhost:5000/")

@click.group(help="CLI tool to interact with key value store")
def cli():
    pass

# Adding commands
cli.add_command(get.get)
cli.add_command(put.put)
cli.add_command(subscribe.subscribe)


if __name__ == '__main__':
cli()