name: Lint Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Requirements
      run: |
        apt install python3-pip
        pip3 install pylint
        pip3 install -r ./requirements.txt
    - name: Run Pylint
      run: |
        pylint ./*.py */*.py kvstore -E